/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.Locale;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Lelamd
 */
public class framcounter extends javax.swing.JFrame {
    public double total=0;
    public double c1=0;
    public double c5=0;
    public double c10=0;
    public double c25=0;
    public double d1=0;
    public double d2=0;
    public double r5=0;
    public double r10=0;
    public double r25=0;
    public double r1=0;
    public double rL=0;
    public double rT=0;
    public double b5=0;
    public double b10=0;
    public double b20=0;
    public double b50=0;
    public double b100=0;
    
    
    /**
     * Creates new form framcounter
     */
    public framcounter() {
        this.setIconImage(Toolkit.getDefaultToolkit() 
  .getImage("cash.gif"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cash Counter");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("1¢");

        jLabel5.setText("5¢");

        jLabel6.setText("10¢");

        jLabel7.setText("25¢");

        jLabel8.setText("1$");

        jLabel9.setText("2$");

        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });

        jTextField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField2CaretUpdate(evt);
            }
        });

        jTextField3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField3CaretUpdate(evt);
            }
        });

        jTextField4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField4CaretUpdate(evt);
            }
        });

        jTextField5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField5CaretUpdate(evt);
            }
        });

        jTextField6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField6CaretUpdate(evt);
            }
        });

        jLabel10.setText("0.00$");

        jLabel11.setText("0.00$");

        jLabel12.setText("0.00$");

        jLabel13.setText("0.00$");

        jLabel14.setText("0.00$");

        jLabel15.setText("0.00$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("1¢");

        jLabel17.setText("5¢");

        jLabel18.setText("10¢");

        jLabel19.setText("25¢");

        jLabel20.setText("1$");

        jLabel21.setText("2$");

        jTextField7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField7CaretUpdate(evt);
            }
        });

        jTextField8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField8CaretUpdate(evt);
            }
        });

        jTextField9.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField9CaretUpdate(evt);
            }
        });

        jTextField10.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField10CaretUpdate(evt);
            }
        });

        jTextField11.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField11CaretUpdate(evt);
            }
        });

        jTextField12.setVerifyInputWhenFocusTarget(false);
        jTextField12.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField12CaretUpdate(evt);
            }
        });

        jLabel22.setText("0.00$");

        jLabel23.setText("0.00$");

        jLabel24.setText("0.00$");

        jLabel25.setText("0.00$");

        jLabel26.setText("0.00$");

        jLabel27.setText("0.00$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setText("5$");

        jLabel29.setText("10$");

        jLabel30.setText("20$");

        jLabel31.setText("50$");

        jLabel32.setText("100$");

        jTextField13.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField13CaretUpdate(evt);
            }
        });

        jTextField14.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField14CaretUpdate(evt);
            }
        });

        jTextField15.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField15CaretUpdate(evt);
            }
        });

        jTextField16.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField16CaretUpdate(evt);
            }
        });

        jTextField17.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField17CaretUpdate(evt);
            }
        });

        jLabel33.setText("0.00$");

        jLabel34.setText("0.00$");

        jLabel35.setText("0.00$");

        jLabel36.setText("0.00$");

        jLabel37.setText("0.00$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Coins");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Coin Rolls");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Bills");

        jLabel38.setText("Float:");

        jTextField18.setText("400");
        jTextField18.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField18CaretUpdate(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setText("Total:");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel40.setText("0.00$");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel41.setText("Total deposit:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel42.setText("-400.00$");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel43.setText("1.0a  By: Leland Peterson for The Source. 055340");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel41)))
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(jLabel42))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
       try{
            String temp;
            int count;
            double value;
            temp = this.jTextField1.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)0.01;
            this.jLabel10.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.c1;
            this.c1 = value;
            this.total+= this.c1;
        }catch(NumberFormatException e){
            this.jLabel10.setText("ERR");
        }
        
          String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTextField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField2CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField2.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)0.05;
            this.jLabel11.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.c5;
            this.c5 = value;
            this.total+= this.c5;
        }catch(NumberFormatException e){
            this.jLabel11.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField2CaretUpdate

    private void jTextField3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField3CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField3.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)0.10;
            this.jLabel12.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.c10;
            this.c10 = value;
            this.total+= this.c10;
        }catch(NumberFormatException e){
            this.jLabel12.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField3CaretUpdate

    private void jTextField4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField4CaretUpdate
       try{
            String temp;
            int count;
            double value;
            temp = this.jTextField4.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)0.25;
            this.jLabel13.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.c25;
            this.c25 = value;
            this.total+= this.c25;
        }catch(NumberFormatException e){
            this.jLabel13.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField4CaretUpdate

    private void jTextField5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField5CaretUpdate
         try{
            String temp;
            int count;
            double value;
            temp = this.jTextField5.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)1.00;
            this.jLabel14.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.d1;
            this.d1 = value;
            this.total+= this.d1;
        }catch(NumberFormatException e){
            this.jLabel14.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField5CaretUpdate

    private void jTextField6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField6CaretUpdate
       try{
            String temp;
            int count;
            double value;
            temp = this.jTextField6.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)2.00;
            this.jLabel15.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.d2;
            this.d2 = value;
            this.total+= this.d2;
        }catch(NumberFormatException e){
            this.jLabel15.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField6CaretUpdate

    private void jTextField18CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField18CaretUpdate
           try{
        
            String total = String.valueOf(String.format("%.2f",this.total));
              this.jLabel40.setText(total +"$");
              int float1 = Integer.parseInt(this.jTextField18.getText());
              String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
              if(ftotal.length()-ftotal.indexOf(".")<3){
                 ftotal=  ftotal + "0";
              }
              this.jLabel42.setText(ftotal+"$");
           }catch (NumberFormatException e){
               
           }
    }//GEN-LAST:event_jTextField18CaretUpdate

    private void jTextField7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField7CaretUpdate
       try{
            String temp;
            int count;
            double value;
            temp = this.jTextField7.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)0.50;
            this.jLabel22.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.r1;
            this.r1 = value;
            this.total+= this.r1;
        }catch(NumberFormatException e){
            this.jLabel22.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField7CaretUpdate

    private void jTextField8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField8CaretUpdate
       try{
            String temp;
            int count;
            double value;
            temp = this.jTextField8.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)2.00;
            this.jLabel23.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.r5;
            this.r5 = value;
            this.total+= this.r5;
        }catch(NumberFormatException e){
            this.jLabel23.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField8CaretUpdate

    private void jTextField9CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField9CaretUpdate
       try{
            String temp;
            int count;
            double value;
            temp = this.jTextField9.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)5.00;
            this.jLabel24.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.r10;
            this.r10 = value;
            this.total+= this.r10;
        }catch(NumberFormatException e){
            this.jLabel24.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField9CaretUpdate

    private void jTextField10CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField10CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField10.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)10.00;
            this.jLabel25.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.r25;
            this.r25 = value;
            this.total+= this.r25;
        }catch(NumberFormatException e){
            this.jLabel25.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField10CaretUpdate

    private void jTextField11CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField11CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField11.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)25.00;
            this.jLabel26.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.rL;
            this.rL = value;
            this.total+= this.rL;
        }catch(NumberFormatException e){
            this.jLabel26.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
         String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField11CaretUpdate

    private void jTextField12CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField12CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField12.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)50.00;
            this.jLabel27.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.rT;
            this.rT = value;
            this.total+= this.rT;
        }catch(NumberFormatException e){
            this.jLabel27.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
        String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField12CaretUpdate

    private void jTextField13CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField13CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField13.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)5.00;
            this.jLabel33.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.b5;
            this.b5 = value;
            this.total+= this.b5;
        }catch(NumberFormatException e){
            this.jLabel33.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
        String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField13CaretUpdate

    private void jTextField14CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField14CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField14.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)10.00;
            this.jLabel34.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.b10;
            this.b10 = value;
            this.total+= this.b10;
        }catch(NumberFormatException e){
            this.jLabel34.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
        String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField14CaretUpdate

    private void jTextField15CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField15CaretUpdate
        try{
            String temp;
            int count;
            double value;
            temp = this.jTextField15.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)20.00;
            this.jLabel35.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.b20;
            this.b20 = value;
            this.total+= this.b20;
        }catch(NumberFormatException e){
            this.jLabel35.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
        String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField15CaretUpdate

    private void jTextField16CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField16CaretUpdate
         try{
            String temp;
            int count;
            double value;
            temp = this.jTextField16.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)50.00;
            this.jLabel36.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.b50;
            this.b50 = value;
            this.total+= this.b50;
        }catch(NumberFormatException e){
            this.jLabel36.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
        String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField16CaretUpdate

    private void jTextField17CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField17CaretUpdate
       try{
            String temp;
            int count;
            double value;
            temp = this.jTextField17.getText();
            if(temp.isEmpty()){
                temp = "0";
            }
            count = Integer.parseInt(temp);
            value = count * (double)100.00;
            this.jLabel37.setText(String.format("%.2f" ,value)+"$");
            this.total -= this.b100;
            this.b100 = value;
            this.total+= this.b100;
        }catch(NumberFormatException e){
            this.jLabel37.setText("ERR");
        }
        
         String total = String.valueOf(String.format("%.2f",this.total));
         this.jLabel40.setText(total +"$");
         int float1 = Integer.parseInt(this.jTextField18.getText());
        String ftotal = String.valueOf(String.format("%.2f", this.total- float1));
         if(ftotal.length()-ftotal.indexOf(".")<3){
            ftotal=  ftotal + "0";
         }
         this.jLabel42.setText(ftotal+"$");
    }//GEN-LAST:event_jTextField17CaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          total=0;
          c1=0;
          c5=0;
          c10=0;
          c25=0;
          d1=0;
          d2=0;
          r5=0;
          r10=0;
          r25=0;
          r1=0;
          rL=0;
          rT=0;
          b5=0;
          b10=0;
          b20=0;
          b50=0;
          b100=0;
          this.jTextField1.setText("");
          this.jTextField2.setText("");
          this.jTextField3.setText("");
          this.jTextField4.setText("");
          this.jTextField5.setText("");
          this.jTextField6.setText("");
          this.jTextField7.setText("");
          this.jTextField8.setText("");
          this.jTextField9.setText("");
          this.jTextField10.setText("");
          this.jTextField11.setText("");
          this.jTextField12.setText("");
          this.jTextField13.setText("");
          this.jTextField14.setText("");
          this.jTextField15.setText("");
          this.jTextField16.setText("");
          this.jTextField17.setText("");
          this.jLabel10.setText("0.00$");
          this.jLabel11.setText("0.00$");
          this.jLabel12.setText("0.00$");
          this.jLabel13.setText("0.00$");
          this.jLabel14.setText("0.00$");
          this.jLabel15.setText("0.00$");
          this.jLabel22.setText("0.00$");
          this.jLabel23.setText("0.00$");
          this.jLabel24.setText("0.00$");
          this.jLabel25.setText("0.00$");
          this.jLabel26.setText("0.00$");
          this.jLabel27.setText("0.00$");
          this.jLabel33.setText("0.00$");
          this.jLabel34.setText("0.00$");
          this.jLabel35.setText("0.00$");
          this.jLabel36.setText("0.00$");
          this.jLabel37.setText("0.00$");
          this.jLabel40.setText("0.00$");
          this.jLabel42.setText("-400.00$");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framcounter().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    public javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField17;
    public javax.swing.JTextField jTextField18;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
